### ISSUE TITLE
How to define a new protocol

### ISSUE THREAD

**Issue by mawenqi** [mesalock-linux/brpc-rs#3]
Is it possible to define a new protocol like [new_protocol](https://github.com/apache/incubator-brpc/blob/master/docs/en/new_protocol.md) in rust? 
or we have to defint it in C++, and re-compile / replace the brpc-sys? 
thanks

**Comment by ymjing** [comment]
No. brpc-rs/brpc-sys is just an FFI shim layer for brpc. If you need a new protocol you would need to implement it in brpc with C++.

This project is not being maintained since I've resigned from Baidu
